console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastel-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  t-foreground = '#a3aed2'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:terminal-magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:terminal-red{{end}}', '{{if eq .Code 0}}p:pistachio-green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }}'
    foreground = 'blue'
    type = 'path'

    [blocks.segments.properties]
      max_depth = 3
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <green>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = 'p:t-foreground'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }} <p:t-foreground>|</>'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    style = 'plain'
    template = '{{if ne .Profile "default"}}  {{ .Profile }}{{end}} 󰒋 {{ .Region }}'
    foreground = 'p:terminal-green'
    background = 'transparent'
    type = 'aws'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}p:terminal-magenta{{end}}']
